server:
  port: 8761
spring:
  application:
    name: eurkea-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false

  instance:
    instance-id: eureka-server-test
    statusPageUrlPath: http://localhost:8761/info
    healthCheckUrlPath: http://localhost:8761/health
    homePageUrl: https://${eureka.hostname}/
